/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface TickerUSDFeedRegistryAbiInterface extends Interface {
  getFunction(
    nameOrSignature: "getTickerFeed" | "setTickerFeed"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "TickerFeedUpdated"): EventFragment;

  encodeFunctionData(
    functionFragment: "getTickerFeed",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setTickerFeed",
    values: [string, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getTickerFeed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTickerFeed",
    data: BytesLike
  ): Result;
}

export namespace TickerFeedUpdatedEvent {
  export type InputTuple = [ticker: string, feedAddress: AddressLike];
  export type OutputTuple = [ticker: string, feedAddress: string];
  export interface OutputObject {
    ticker: string;
    feedAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TickerUSDFeedRegistryAbi extends BaseContract {
  connect(runner?: ContractRunner | null): TickerUSDFeedRegistryAbi;
  waitForDeployment(): Promise<this>;

  interface: TickerUSDFeedRegistryAbiInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getTickerFeed: TypedContractMethod<[ticker: string], [string], "view">;

  setTickerFeed: TypedContractMethod<
    [ticker: string, feedAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getTickerFeed"
  ): TypedContractMethod<[ticker: string], [string], "view">;
  getFunction(
    nameOrSignature: "setTickerFeed"
  ): TypedContractMethod<
    [ticker: string, feedAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "TickerFeedUpdated"
  ): TypedContractEvent<
    TickerFeedUpdatedEvent.InputTuple,
    TickerFeedUpdatedEvent.OutputTuple,
    TickerFeedUpdatedEvent.OutputObject
  >;

  filters: {
    "TickerFeedUpdated(string,address)": TypedContractEvent<
      TickerFeedUpdatedEvent.InputTuple,
      TickerFeedUpdatedEvent.OutputTuple,
      TickerFeedUpdatedEvent.OutputObject
    >;
    TickerFeedUpdated: TypedContractEvent<
      TickerFeedUpdatedEvent.InputTuple,
      TickerFeedUpdatedEvent.OutputTuple,
      TickerFeedUpdatedEvent.OutputObject
    >;
  };
}
