/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  TickerUSDFeedRegistryAbi,
  TickerUSDFeedRegistryAbiInterface,
} from "../abi/TickerUSDFeedRegistryAbi";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "string",
        name: "ticker",
        type: "string",
      },
      {
        indexed: false,
        internalType: "address",
        name: "feedAddress",
        type: "address",
      },
    ],
    name: "TickerFeedUpdated",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "ticker",
        type: "string",
      },
    ],
    name: "getTickerFeed",
    outputs: [
      {
        internalType: "address",
        name: "feedAddress",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "ticker",
        type: "string",
      },
      {
        internalType: "address",
        name: "feedAddress",
        type: "address",
      },
    ],
    name: "setTickerFeed",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class TickerUSDFeedRegistryAbi__factory {
  static readonly abi = _abi;
  static createInterface(): TickerUSDFeedRegistryAbiInterface {
    return new Interface(_abi) as TickerUSDFeedRegistryAbiInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): TickerUSDFeedRegistryAbi {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as TickerUSDFeedRegistryAbi;
  }
}
